### ISSUE TITLE
lcheader crashes

### ISSUE THREAD

**Issue by WayneCrawford** [WayneCrawford/lcheapo#5]
Interface with sdpchain probably not updated.  The error is:

```
(obspy) mac-wayne-1:tests 512> lcheader --no_questions
Traceback (most recent call last):
  File "/Users/crawford/opt/anaconda3/envs/obspy/bin/lcheader", line 33, in <module>
    sys.exit(load_entry_point('lcheapo', 'console_scripts', 'lcheader')())
  File "/Users/crawford/_Work/Programming/lcheapo/lcheapo/lcheader.py", line 33, in main
    opts = __getOptions()
  File "/Users/crawford/_Work/Programming/lcheapo/lcheapo/lcheader.py", line 149, in __getOptions
    args.in_dir, args.out_dir, _ = ProcessStep.setup_paths(args)
  File "/Users/crawford/_Work/Programming/lcheapo/lcheapo/sdpchain/process_steps.py", line 180, in setup_paths
    raise NameError('args has no input_files attribute')
NameError: args has no input_files attribute
```

**Comment by WayneCrawford** [comment]
Richard Dreo has a similar (same) problem with lc2SDS_weak on the pip version (1.0.4):

```
$ lc2ms_weak -h 
Traceback (most recent call last): 
  File "/home/richard/anaconda3/envs/env_rhumrum/bin/lc2ms_weak", line 
5, in <module> 
    from lcheapo.lc2ms import lc2ms 
  File "<fstring>", line 1 
    (args.infiles=) 
                 ^ 
SyntaxError: invalid syntax 
```

should also remove lcheapo 1.0.4 from pypi once I've got a working version

**Comment by WayneCrawford** [comment]
- [x] Add script error checker to tests
- [x] Fix this error
- [x] Remove lcheapo v1.0.4 from PyPi
